; PlatformIO project configuration for Rubber Otter
; Default set to pro_micro_hid with HID-Project library enabled for full macOS / Windows / Linux Consumer Media Key support.

[platformio]
default_envs = pro_micro_hid

[env:pro_micro_hid]
platform = atmelavr
board = sparkfun_promicro16  ; use sparkfun_promicro8 for 3.3V/8MHz variants
framework = arduino
monitor_speed = 115200
build_flags =
  -D USE_SOFTSERIAL
  -D USE_HID_PROJECT
  -D BLE_NAME=\"Otter\"
lib_deps =
  SoftwareSerial
  HID-Project

[env:leonardo_hid]
platform = atmelavr
board = leonardo
framework = arduino
monitor_speed = 115200
build_flags =
  -D USE_SOFTSERIAL
  -D USE_HID_PROJECT
  -D BLE_NAME=\"Otter\"
lib_deps =
  SoftwareSerial
  HID-Project

[env:pro_micro]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
monitor_speed = 115200
build_flags =
  -D USE_SOFTSERIAL
  -D BLE_NAME=\"Otter\"
lib_deps =
  Keyboard
  Mouse
  SoftwareSerial

[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino
monitor_speed = 115200
build_flags =
  -D USE_SOFTSERIAL
  -D BLE_NAME=\"Otter\"
lib_deps =
  Keyboard
  Mouse
  SoftwareSerial
